# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.2.0
_src_path: git@github.com:datalab-org/datalab-app-plugin-template
author_email: ben.ed.smith@mac.com
author_fullname: Ben Smith
copyright_date: 19/12/2025
copyright_holder: Ben Smith
copyright_holder_email: ben.ed.smith@mac.com
package_name: datalab_app_plugin_oms
project_name: datalab-app-plugin-oms
repository_name: datalab-app-plugin-oms
repository_namespace: be-smith
short_description: datalab-app-plugin-oms.

